[package]
name = "hsrm-internship-report"
version = "0.0.3"
entrypoint = "template.typ"
authors = ["Leonard H. <@leonardhwg>"]
license = "MIT"
description = "Internship report for HSRM's work-integrated study program"
repository = "https://github.com/leonardhwg/hsrm-internship-report"
keywords = ["hsrm", "praxisbericht", "duale studium", "hochschule rhein-main", "dual study", "work integrated report"]
categories = ["report"]
disciplines  = ["computer-science"]
exclude = ["main.pdf"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"

[tool.packager]
paths = [
  "template.typ",
  "data.typ",
  "template",
  "README.md",
  "thumbnail.png",
  "generic-company-logo.png",
  "generic-uni-logo.png",
  "author-marker.typ",
  "template/main.typ"
]
